// This file is automatically generated by Firebase Studio.
// Do not edit manually.

// Follow the instructions in the Firebase console to configure your app.
// You'll need to install the Firebase CLI and login to your account.
// Then, you can run `firebase apps:sdkconfig` to get your configuration.

// Ensure you have a `.env.local` file with your Firebase configuration.
// See `.env.local.example` for the required format.

const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

export function getFirebaseConfig() {
  if (!firebaseConfig.apiKey) {
    throw new Error('Missing Firebase config: `NEXT_PUBLIC_FIREBASE_API_KEY`');
  }
  return firebaseConfig;
}
